### ISSUE TITLE
Run install-urbit.sh on start.sh

### ISSUE THREAD

**Issue by arguser** [mopfel-winrux/urbit-umbrel#13]
If we avoid having Urbit being part of the image and instead install it on Container initialization we shouldn't need to wait for an Umbrel release for having an updated Urbit binary.

**Comment by arguser** [comment]
Maybe something looking like https://github.com/mopfel-winrux/urbit-umbrel/pull/15

**Comment by mopfel-winrux** [comment]
merged this
