### ISSUE TITLE
Release version 1.9 of Urbit for aarch64

### ISSUE THREAD

**Issue by piraces** [mopfel-winrux/urbit-umbrel#14]
First of all thank you for your great effort!

For users running umbrel in a Raspberry Pi in an `aarch64` architecture, the binary is retrieved from this fork: https://github.com/botter-nidnul/urbit

I think we need @botter-nidnul to rebase its fork and release the binary, then the following lines should be updated:

https://github.com/mopfel-winrux/urbit-umbrel/blob/9acf74fcd77c9a44bdb8e71fa9c52c8baffca38c/install-urbit.sh#L7-L8

**Comment by botter-nidnul** [comment]
Yes. Working on it now.

**Comment by mopfel-winrux** [comment]
Umbrel app is updated to have the latest urbit binary
