### ISSUE TITLE
pier won't boot

### ISSUE THREAD

**Issue by seminalentropy** [mopfel-winrux/urbit-umbrel#16]
My pier won't boot

Umbrel version 0.5

urbit 1.9
boot: home is /data/piers/[redacted]
loom: mapped 2048MB
lite: arvo formula 11a9e7fe
lite: core 38d4ad4d
lite: final state 38d4ad4d
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.596.211.200
Assertion '!"loom: corrupt"' failed in noun/allocate.c:138
home: bailing out
pier: serf unexpectedly shut down

**Comment by seminalentropy** [comment]
after deleting north.bin and south.bin I get this

---------------- playback complete ----------------
vere: checking version compatibility
pier: version negotation failed

wyrd: bail 1

[%poke %wyrd]
wyrd: bail: %exit
wyrd: %wyrd event on /arvo failed

**Comment by mopfel-winrux** [comment]
Hi @seminalentropy This is looking like an Urbit Pier issue. I would remote into the umbrel and copy over your pier and work on fixing it through that. I'm not sure I can help you debug an issue with your ship.
