### ISSUE TITLE
Release Urbit v1.10?

### ISSUE THREAD

**Issue by ar-jan** [mopfel-winrux/urbit-umbrel#18]
Will you be releasing an update with Urbit v. 1.10?

I was also wondering what the relationship is between the Urbit version shipped via Docker and Urbit OTA updates (how important is an up-to-date docker image?), and also: could this app be built upon the tloncorp/urbit Docker image?

**Comment by mopfel-winrux** [comment]
Hey, yea I need to find time to do this. The official Tlon docker image doesn't include AARCH64 support so we have to do make our own. I need to update the binary and this docker image to support v1.10
