### ISSUE TITLE
Latest Release (v1.16 update) Not Working

### ISSUE THREAD

**Issue by hanryc-tirpur** [mopfel-winrux/urbit-umbrel#21]
Hello,

I just installed the v1.16 update and now my moon will not boot. I checked the logs and am getting this message

```
127.0.0.1 - - [15/Jan/2023 20:16:20] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [15/Jan/2023 20:16:20] "GET /static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [15/Jan/2023 20:16:20] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [15/Jan/2023 20:17:16] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [15/Jan/2023 20:17:16] "GET /static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [15/Jan/2023 20:17:16] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [15/Jan/2023 20:17:35] "POST /boot HTTP/1.0" 302 -
Urbit detected a Pier named /data/piers/modlyx-hidled-hanryc-tirpur/
./boot_pier.sh: line 6: urbit: command not found
```

Any ideas?

**Comment by yapishu** [comment]
Ahh I know exactly what the issue is -- the binary repo moved to `urbit/vere` and we didn't update the URL. Hang tight and I will PR

**Comment by yapishu** [comment]
(btw your pier is still in place and you didn't lose anything, but I apologize for the inconvenience)

**Comment by yapishu** [comment]
https://github.com/getumbrel/umbrel-apps/pull/371

**Comment by yapishu** [comment]
@hanryc-tirpur in the meantime you should be able to manually edit your urbit app's compose file to use this image:

`umbrel:v1.16@sha256:f8c746b2c85336cbf5049ee88e2fea7c5aaa8d952da2a8a327cbeb0cfea06c41`

**Comment by hanryc-tirpur** [comment]
Quick service! Thanks!

**Comment by yapishu** [comment]
@hanryc-tirpur hotfix has been merged
