### ISSUE TITLE
v1.19 Not finding ./boot_pier.sh

### ISSUE THREAD

**Issue by hanryc-tirpur** [mopfel-winrux/urbit-umbrel#23]
Hello! Me, again. After installing the v1.19 update on Umbrel, I am not able to boot and this is the error I am getting. Not sure if they changed the url again like #21 , or if this is another issue.

```
127.0.0.1 - - [12/Feb/2023 23:00:23] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [12/Feb/2023 23:00:23] "GET /static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [12/Feb/2023 23:00:23] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [12/Feb/2023 23:00:26] "POST /boot HTTP/1.0" 302 -
Urbit detected a Pier named /data/piers/modlyx-hidled-hanryc-tirpur/
./boot_pier.sh: line 6: urbit: command not found
```

**Comment by yapishu** [comment]
Hmm, I just pulled the x64 Docker image and it definitely has the binary:

```
❯ docker exec -it d87354a1f548 /bin/bash
root@d87354a1f548:/# urbit
Urbit: a personal server operating function
https://urbit.org
Version 1.19
```

same on an arm64 box:
```
np@np-build:~/$ docker exec -it 2e937a893042 /bin/bash
root@2e937a893042:/# urbit
Urbit: a personal server operating function
https://urbit.org
Version 1.19
```

Can you try getting a shell inside your Urbit container and seeing if the binary is present? Also, what is the output of `uname -m` on your Umbrel device?

**Comment by hanryc-tirpur** [comment]
`uname -m` gives `aarch64`

When I log into the docker container, this is what I see.

```
umbrel@umbrel:~/umbrel $ docker exec -it 414a6f42b521 /bin/bash
root@414a6f42b521:/# ls
app  boot  dev	home  media  opt   requirements.txt  run   srv	tmp    usr
bin  data  etc	lib   mnt    proc  root		     sbin  sys	urbit  var
root@414a6f42b521:/# ls urbit/
binary
root@414a6f42b521:/# ls urbit/binary/
vere-v1.19-linux-aarch64.1
root@414a6f42b521:/# urbit/
bash: urbit/: Is a directory
```

**Comment by yapishu** [comment]
Hm, for some reason on your box it looks like the vere binary has a `.1` extension that shouldn't be there. Are you able to execute it with `./vere-v1.19-linux-aarch64.1`? If so, try running `mv vere-v1.19-linux-aarch64.1 /usr/sbin/urbit` then restarting the container. I'm not sure why the file name is irregular.

**Comment by hanryc-tirpur** [comment]
Moving the binary solved the issue. How weird. Thanks, once again, for the help!

**Comment by yapishu** [comment]
I suspect it has something to do with an incomplete extraction process but googling has not revealed much
