### ISSUE TITLE
Disable Urbit Auth on next update

### ISSUE THREAD

**Issue by JohncomQ** [mopfel-winrux/urbit-umbrel#24]
Hi ~mopfel-winrux,

would it be possible to disable the Umbrel auth for the urbit app with the next update? This causes some friction with apps like holium.

![image](https://user-images.githubusercontent.com/93653763/224732319-75c22768-e10e-42ce-aa80-a9ca349c2fea.png)

Thanks a lot :)

**Comment by yapishu** [comment]
This has been merged into the vere 2.0 release https://github.com/getumbrel/umbrel-apps/pull/464
