### ISSUE TITLE
Permissions issue when booting from keyfile

### ISSUE THREAD

**Issue by cdkocher** [mopfel-winrux/urbit-umbrel#25]
I'm running Umbrel version 0.5.3, with Urbit v2.0. When trying to boot from a keyfile, I upload the file (following the naming convention) then press boot and nothing happens. When looking into the server logs, I see it is doing the following:

POST request to /boot
Urbit will use /data/keys/sampel-palnet.key to create a pier and then restart. Please wait while it initializes your ship. 
./boot_key.sh: line 8: /usr/sbin/urbit: Permission denied

These are all fresh installs, so I think the app has a permissions issue when installing. I'm sure I could find a workaround, but the point is that no command line is needed for the install, so I think this warrants a fix on the development end.

**Comment by cdkocher** [comment]
Great, I no longer get the permissions issue. I have a pier now. When I boot that, I get the spinning urbit icon. In the server logs, it says the web interface, the loopback, and the pier are all live. Is this the expected behavior, or is landscape supposed to show up when I boot?

**Comment by yapishu** [comment]
Once the web interface is live, the spinning icon screen should refresh redirect to a different page with your login +code and a link to Landscape

**Comment by cdkocher** [comment]
I opened the app the next day and landscape was there. Seems like it just needed some time to load up. All issues seem to be resolved, thanks for your help.
