### ISSUE TITLE
after update no longer able to boot

### ISSUE THREAD

**Issue by CryptoSocks** [mopfel-winrux/urbit-umbrel#27]
as title states i am unable to boot planets or comets on the umbrel app after the last update the troubleshooting logs state that urbit is not found in all the boot bash scripts.
e.g. 
manager_1     | ./boot_pier.sh: line 6: urbit: command not found

**Comment by yapishu** [comment]
Oof, that's annoying, sorry for the inconvenience. Our build pipeline must have spit out something bad. Looking into this.

**Comment by yapishu** [comment]
FYI, this was because the Vere repo tagged a release without actually posting the binary, which set off a false trigger on our end. I've submitted a reverted PR to Umbrel https://github.com/getumbrel/umbrel-apps/pull/512

**Comment by CryptoSocks** [comment]
thanks for the update wasn't sure if i should try to reinstall the app, i didn't want to risk losing my pier.

**Comment by yapishu** [comment]
2.3 has been merged
