### ISSUE TITLE
Clicking boot, nothing happens

### ISSUE THREAD

**Issue by velamvela** [mopfel-winrux/urbit-umbrel#5]
Uploaded a keyfile, clicked boot, bottom ~ spins for a bit and then nothing happens....

Is there a user guide somewhere?

**Comment by mopfel-winrux** [comment]
Sorry there is not. When you upload a keyfile it should boot a ship, exit, and delete the keyfile. this stops you from booting the same ship twice and needing to breach. Can you refresh the page and see if the pier is populated?

**Comment by velamvela** [comment]
refreshing the page just takes me to the same page without a keyfile/the default screen. let me know how i can help troubleshoot this


<img width="518" alt="Screen Shot 2022-02-23 at 9 46 44 am" src="https://user-images.githubusercontent.com/85039592/155216489-9890916c-0959-45e1-b04d-aa7af06c4ae4.png">
s

**Comment by mopfel-winrux** [comment]
Can you ssh into the raspberry pi and run:

` docker logs urbit_manager_1`

and give me the output. The upload a rekeyed moon file and boot it up and run the same command as above.

**Comment by velamvela** [comment]
127.0.0.1 - - [23/Feb/2022 03:23:58] "POST //upload_key HTTP/1.0" 302 -
127.0.0.1 - - [23/Feb/2022 03:23:58] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [23/Feb/2022 03:23:59] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [23/Feb/2022 03:23:59] "GET / HTTP/1.0" 200 -
Urbit will use /data/keys/dinnul-namrud.key to create a pier and then restart. Please wait while it initializes your ship.
127.0.0.1 - - [23/Feb/2022 03:24:16] "POST //boot HTTP/1.0" 302 -
~
127.0.0.1 - - [23/Feb/2022 03:24:16] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [23/Feb/2022 03:24:17] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [23/Feb/2022 03:24:17] "GET / HTTP/1.0" 200 -
urbit 1.8
boot: home is /app//data/piers/[redacted]
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
boot: downloading pill https://bootstrap.urbit.org/urbit-v1.8.pill
failed to fetch https://bootstrap.urbit.org/urbit-v1.8.pill: Couldn't resolve host name
Urbit will delete the key for security reasons.
127.0.0.1 - - [23/Feb/2022 03:24:24] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [23/Feb/2022 03:24:24] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [23/Feb/2022 03:24:25] "GET / HTTP/1.0" 200 -

**Comment by velamvela** [comment]
wget fails also

wget https://bootstrap.urbit.org/urbit-v1.8.pill
--2022-02-23 03:31:00--  https://bootstrap.urbit.org/urbit-v1.8.pill
Resolving bootstrap.urbit.org (bootstrap.urbit.org)... 104.21.64.85, 172.67.179.114
Connecting to bootstrap.urbit.org (bootstrap.urbit.org)|104.21.64.85|:443... connected.
GnuTLS: Error in the pull function.
Unable to establish SSL connection.

**Comment by mopfel-winrux** [comment]
It looks like something in your network is blocking urbit from downloading the bootstrap pill. The wget command looks to be a TLS error on your OS. 

Are you running this on a Pi or VM?

**Comment by velamvela** [comment]
Seems to have worked today but now having this error:

failed to fetch https://roller.urbit.org/v1/azimuth: Couldn't resolve host name

**Comment by velamvela** [comment]
Running on Pi

**Comment by yapishu** [comment]
@velamvela this seems to be a DNS issue outside of the app -- are you able to perform `nslookup roller.urbit.org` from a shell on your Pi?

**Comment by velamvela** [comment]
tried again and seems to be working now...not sure whats going on there

i think the pier has populated now though, will close this when/if it boots

**Comment by tarnec-monmec** [comment]
I am having this same issue which I can't resolve.

Here's the output of docker:

umbrel@umbrel:~ $ docker logs urbit_manager_1
Adding password for user umbrel
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://10.21.21.76:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Feb/2022 00:01:51] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:01:51] "GET //static/logo.png HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:01:51] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:02:30] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:03:31] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:03:31] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:03:31] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:04:32] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:04:32] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:04:32] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:05:33] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:05:33] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:05:33] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:06:34] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:06:34] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:06:34] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:07:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:07:35] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:07:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:08:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:08:36] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:08:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:09:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:09:36] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:09:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:10:00] "POST //upload_key HTTP/1.0" 302 -
127.0.0.1 - - [28/Feb/2022 00:10:00] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:10:01] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:10:01] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:10:23] "POST //upload_key HTTP/1.0" 302 -
127.0.0.1 - - [28/Feb/2022 00:10:23] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:10:24] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:10:24] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:10:31] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:10:31] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:10:31] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:10:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:10:35] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:10:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:10:41] "POST //boot HTTP/1.0" 400 -
127.0.0.1 - - [28/Feb/2022 00:10:42] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:10:46] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:11:30] "POST //boot HTTP/1.0" 400 -
127.0.0.1 - - [28/Feb/2022 00:11:30] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:11:33] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:12:33] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:12:34] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:12:34] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:13:34] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:13:34] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:13:34] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:14:34] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:14:34] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:14:34] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:15:34] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:15:34] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:15:34] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:16:34] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:16:35] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:16:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:17:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:17:35] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:17:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:18:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:18:35] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:18:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:19:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:19:35] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:19:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:20:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:20:35] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:20:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:21:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:21:35] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:21:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:22:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:22:36] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:22:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:23:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:23:36] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:23:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:24:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:24:36] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:24:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:25:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:25:36] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:25:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:26:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:26:36] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:26:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:27:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:27:37] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:27:37] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:28:37] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:28:37] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:28:37] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:29:37] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:29:37] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:29:37] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:30:37] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:30:38] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:30:38] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:31:38] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:31:38] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:31:38] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:32:38] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:32:39] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:32:39] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:33:39] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:33:39] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:33:39] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:34:39] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:34:39] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:34:39] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:35:39] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:35:39] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:35:39] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:36:39] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:36:40] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:36:40] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:37:40] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:37:40] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:37:40] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:38:40] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:38:40] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:38:40] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:39:40] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:39:40] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:39:40] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:40:40] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:40:40] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:40:40] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:41:40] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:41:41] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:41:41] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:42:41] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:42:41] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:42:41] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:43:41] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:43:41] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:43:41] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:44:41] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:44:41] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:44:41] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:45:41] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:45:42] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:45:42] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:46:42] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:46:42] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:46:42] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:47:42] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:47:42] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:47:42] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:48:42] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:48:42] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:48:42] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:49:42] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:49:42] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:49:42] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:50:42] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:50:43] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:50:43] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:51:43] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:51:43] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:51:43] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:52:43] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:52:43] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:52:43] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:53:43] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:53:43] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:53:43] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:54:43] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:54:44] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:54:44] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:55:44] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 00:55:44] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 00:55:44] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 22:59:04] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 22:59:04] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 22:59:04] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 22:59:18] "POST //upload_key HTTP/1.0" 302 -
127.0.0.1 - - [28/Feb/2022 22:59:18] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 22:59:18] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 22:59:18] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 22:59:27] "POST //boot HTTP/1.0" 400 -
127.0.0.1 - - [28/Feb/2022 22:59:28] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 22:59:33] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 22:59:45] "POST //boot HTTP/1.0" 400 -
127.0.0.1 - - [28/Feb/2022 22:59:45] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 22:59:47] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 22:59:55] "POST //upload_key HTTP/1.0" 302 -
127.0.0.1 - - [28/Feb/2022 22:59:55] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 22:59:55] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 22:59:56] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:04:51] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:04:53] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:04:53] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:04:59] "POST //boot HTTP/1.0" 302 -
Urbit will use /data/keys/tarnec-monmec-2.key to create a pier and then restart. Please wait while it initializes your ship.
127.0.0.1 - - [28/Feb/2022 23:04:59] "GET / HTTP/1.0" 200 -
~
127.0.0.1 - - [28/Feb/2022 23:04:59] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:04:59] "GET / HTTP/1.0" 200 -
urbit 1.8
boot: home is /app//data/piers/tarnec-monmec-2
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
dawn: invalid ship specified with -w ~tarnec-monmec-2
Urbit will delete the key for security reasons.
127.0.0.1 - - [28/Feb/2022 23:06:00] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:06:00] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:06:00] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:07:00] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:07:00] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:07:01] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:07:14] "POST //upload_key HTTP/1.0" 302 -
127.0.0.1 - - [28/Feb/2022 23:07:14] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:07:14] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:07:14] "GET / HTTP/1.0" 200 -
Urbit will use /data/keys/tarnec-monmec-2.key to create a pier and then restart. Please wait while it initializes your ship.
127.0.0.1 - - [28/Feb/2022 23:07:18] "POST //boot HTTP/1.0" 302 -
~
127.0.0.1 - - [28/Feb/2022 23:07:18] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:07:18] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:07:18] "GET / HTTP/1.0" 200 -
urbit 1.8
boot: home is /app//data/piers/tarnec-monmec-2
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
dawn: invalid ship specified with -w ~tarnec-monmec-2
Urbit will delete the key for security reasons.
127.0.0.1 - - [28/Feb/2022 23:08:19] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:08:19] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:08:19] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:09:20] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:09:20] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:09:20] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:10:21] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:10:21] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:10:21] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:11:22] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:11:22] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:11:22] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:12:23] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:12:23] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:12:23] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:13:24] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:13:24] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:13:24] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:14:25] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:14:25] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:14:25] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:15:26] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:15:26] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:15:26] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:16:27] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:16:27] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:16:27] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:17:28] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [28/Feb/2022 23:17:28] "GET //static/logo.png HTTP/1.0" 304 -
127.0.0.1 - - [28/Feb/2022 23:17:28] "GET / HTTP/1.0" 200 -

**Comment by yapishu** [comment]
Hi there, this is occurring because the app interprets the name of your
ship from the keyfile name. Change the keyfile to tarnec-monmec.key
