### ISSUE TITLE
Size limitation with regard to pier uploading

### ISSUE THREAD

**Issue by brickfrog** [mopfel-winrux/urbit-umbrel#6]
Was curious if this is a known issue, but seem to get nginx size limitation issues when doing a pier upload of ~500 megs. 

Was trying to move from port (desktop) to my umbrel (pi) - didn't know if maybe manual SFTP uploading was an option, but then the boot button doesn't recognize it after unless it (I'm assuming) was done via the flask app.

**Comment by mopfel-winrux** [comment]
Hello, Yes this is a known issue with the original release.
 I put in a pull request for v0.2.0 which fixes this.

 You can however manually place the pier, through `scp` or whatever method you would like, in `~/umbrel/app-data/urbit/piers/`. Afterwards you should be able to refresh the page and the pier will show up and be ready to boot.

**Comment by brickfrog** [comment]
Ah, it wasn't showing up for me after uploading but I realized this might be a permissions issue. Will double check and close if I get it working.

**Comment by brickfrog** [comment]
Ah, darn. Doesn't seem to show up.

![image](https://user-images.githubusercontent.com/9146678/155822540-0b114ca3-c8d6-43d6-9448-f0087867e1ab.png)
![image](https://user-images.githubusercontent.com/9146678/155822706-8b70b31f-c8d5-49c4-9e67-1f8e4a03a4d8.png)

**Comment by mopfel-winrux** [comment]
Can you unzip it?

**Comment by brickfrog** [comment]
Had the idea to do that just after I posted. I assume it unzips as part of the app step?

Aaand that was it.

Welp. Hopefully this will be helpful to anyone who wanders in before the patch gets uploaded.
